### user_Kiosk_Check

POST http://localhost:8080/kiosk/check/1
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJldUxqVlJKSzhrcTV2OXJQdnowbjNRLzRRM08xMTZZTkdrbkpsckdpZlJrPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiVVNFUiIsImlhdCI6MTY4MjI2ODcxMCwiZXhwIjoxNjgyMzU1MTEwfQ.4fKdzhATiwVNniNN8KP8WF7J5dNuYg_e5iVNWdDE5Nk
